# This file was generated by GoReleaser. DO NOT EDIT.
cask "leak" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9a69dda807966888f61254064f0e48a24c3e6bc7146171037188466dfd29adb4"
      url "https://github.com/RishikeshSreekumar/leak/releases/download/v#{version}/leak_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7ab2a9cc8a4e09bc373f3a907e0a2bd3e28371de67b44dcb43b43467fa449daf"
      url "https://github.com/RishikeshSreekumar/leak/releases/download/v#{version}/leak_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e3e9220984b83dda4aec6081bbd0af7620532f3e2f3ffc23b9fb2003e27d606"
      url "https://github.com/RishikeshSreekumar/leak/releases/download/v#{version}/leak_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a78e04237d05fed8216f6e360f108303e30d96ff918e5b6ced948a1d1bbde8b0"
      url "https://github.com/RishikeshSreekumar/leak/releases/download/v#{version}/leak_#{version}_linux_arm64.tar.gz"
    end
  end

  name "leak"
  desc "Mark. Sweep. Save. — a terminal-first subscription manager."
  homepage "https://github.com/RishikeshSreekumar/leak"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "leak"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/leak"]
    end
  end

  # No zap stanza required

end
